CREATE SCHEMA `PROVIDERDB`;

CREATE TABLE `PROVIDERDB`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC)
);

CREATE TABLE `PROVIDERDB`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `PASSWORD` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `EMAIL` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `FIRST_NAME` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `LAST_NAME` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`LOGIN` ASC),
  INDEX `ROLE_ID_idx` (`ROLE_ID` ASC),
  CONSTRAINT `ROLE_ID`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `PROVIDERDB`.`ROLE` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);
